### ISSUE TITLE
Dashboard loads too much data

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#28] opened 2016-11-09 14:32 UTC
There is a lot of time a user waits upon login until dashboard is shown. Debugging has revealed that there is 1 MB data loaded just to show the top 5 orgas.

- [x] ready to fix
- [ ] fixed

**Comment by friedrichweise** [comment] 2017-01-12 18:08
Duplicate of #65

**Closed by friedrichweise** 2017-01-12 18:08 UTC
Labels: enhancement, UI
